// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StorePos.Persistence.Context;

#nullable disable

namespace StorePos.Persistence.Migrations
{
    [DbContext(typeof(StorePosDbContext))]
    [Migration("20260825205325_HardenFinancialIntegrity")]
    partial class HardenFinancialIntegrity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StorePos.Domain.Aggregates.Customer.Customer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdentificationNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Information")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("IdentificationNumber")
                        .IsUnique()
                        .HasFilter("[IdentificationNumber] IS NOT NULL");

                    b.HasIndex("Name");

                    b.ToTable("Customers", "dbo");
                });

            modelBuilder.Entity("StorePos.Domain.Aggregates.MeasurementUnit.MeasurementUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ShortName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Units", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(2026, 8, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "ცალი",
                            ShortName = "ც"
                        },
                        new
                        {
                            Id = 2,
                            DateCreated = new DateTime(2026, 8, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "კილოგრამი",
                            ShortName = "კგ"
                        },
                        new
                        {
                            Id = 3,
                            DateCreated = new DateTime(2026, 8, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "მეტრი",
                            ShortName = "მ"
                        },
                        new
                        {
                            Id = 4,
                            DateCreated = new DateTime(2026, 8, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "ლიტრი",
                            ShortName = "ლ"
                        },
                        new
                        {
                            Id = 5,
                            DateCreated = new DateTime(2026, 8, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "გრამი",
                            ShortName = "გრ"
                        },
                        new
                        {
                            Id = 6,
                            DateCreated = new DateTime(2026, 8, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "ტონა",
                            ShortName = "ტ"
                        },
                        new
                        {
                            Id = 7,
                            DateCreated = new DateTime(2026, 8, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "წყვილი (2 ცალი)",
                            ShortName = "წყ"
                        },
                        new
                        {
                            Id = 8,
                            DateCreated = new DateTime(2026, 8, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "სანტიმეტრი",
                            ShortName = "სმ"
                        },
                        new
                        {
                            Id = 9,
                            DateCreated = new DateTime(2026, 8, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "კვადრატული მეტრი",
                            ShortName = "კვ.მ"
                        },
                        new
                        {
                            Id = 10,
                            DateCreated = new DateTime(2026, 8, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "ყუთი",
                            ShortName = "ყთ"
                        },
                        new
                        {
                            Id = 11,
                            DateCreated = new DateTime(2026, 8, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "ქილა",
                            ShortName = "ქ"
                        },
                        new
                        {
                            Id = 12,
                            DateCreated = new DateTime(2026, 8, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "ბოთლი",
                            ShortName = "ბთ"
                        },
                        new
                        {
                            Id = 13,
                            DateCreated = new DateTime(2026, 8, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "კილომეტრი",
                            ShortName = "კმ"
                        },
                        new
                        {
                            Id = 14,
                            DateCreated = new DateTime(2026, 8, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "კვადრატული სანტიმეტრი",
                            ShortName = "კვ.სმ"
                        },
                        new
                        {
                            Id = 15,
                            DateCreated = new DateTime(2026, 8, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "კუბური მეტრი",
                            ShortName = "კბ.მ"
                        },
                        new
                        {
                            Id = 16,
                            DateCreated = new DateTime(2026, 8, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "მილილიტრი",
                            ShortName = "მმ"
                        },
                        new
                        {
                            Id = 17,
                            DateCreated = new DateTime(2026, 8, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "სხვა",
                            ShortName = "სხვ"
                        },
                        new
                        {
                            Id = 18,
                            DateCreated = new DateTime(2026, 8, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "ჭიქა",
                            ShortName = "ჭიქა"
                        },
                        new
                        {
                            Id = 19,
                            DateCreated = new DateTime(2026, 8, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "კომპლექტი",
                            ShortName = "კომპლექტი"
                        },
                        new
                        {
                            Id = 20,
                            DateCreated = new DateTime(2026, 8, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "რულონი",
                            ShortName = "რულონი"
                        },
                        new
                        {
                            Id = 21,
                            DateCreated = new DateTime(2026, 8, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "ტომარა",
                            ShortName = "ტომარა"
                        },
                        new
                        {
                            Id = 22,
                            DateCreated = new DateTime(2026, 8, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "შეკვრა",
                            ShortName = "შეკვრა"
                        },
                        new
                        {
                            Id = 24,
                            DateCreated = new DateTime(2026, 8, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "მ³",
                            ShortName = "მ³"
                        });
                });

            modelBuilder.Entity("StorePos.Domain.Aggregates.Product.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Barcode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MeasurementUnitId")
                        .HasColumnType("int")
                        .HasColumnName("UnitId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 5)
                        .HasColumnType("decimal(18,5)");

                    b.HasKey("Id");

                    b.HasIndex("Barcode");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("MeasurementUnitId");

                    b.HasIndex("Name");

                    b.ToTable("Products", "dbo");
                });

            modelBuilder.Entity("StorePos.Domain.Aggregates.Sale.Sale", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("CashierId")
                        .HasColumnType("bigint");

                    b.Property<string>("Comment")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<long?>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<string>("CustomerIdentificationNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime?>("DateCancelled")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateCompleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<long>("FinancialRevision")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SaleNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CashierId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DateCreated");

                    b.HasIndex("SaleNumber")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("Sales", "dbo");
                });

            modelBuilder.Entity("StorePos.Domain.Aggregates.Sale.SaleItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Barcode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsManual")
                        .HasColumnType("bit");

                    b.Property<decimal>("LineTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("MeasurementUnitId")
                        .HasColumnType("int")
                        .HasColumnName("UnitId");

                    b.Property<string>("MeasurementUnitName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("UnitName");

                    b.Property<string>("ProductCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long?>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 5)
                        .HasColumnType("decimal(18,5)");

                    b.Property<long>("SaleId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 5)
                        .HasColumnType("decimal(18,5)");

                    b.HasKey("Id");

                    b.HasIndex("MeasurementUnitId");

                    b.HasIndex("ProductId");

                    b.HasIndex("SaleId");

                    b.ToTable("SaleItems", "dbo");
                });

            modelBuilder.Entity("StorePos.Domain.Aggregates.Sale.SalePayment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("OperationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PaymentKind")
                        .HasColumnType("int");

                    b.Property<int>("PaymentType")
                        .HasColumnType("int");

                    b.Property<long>("SaleId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OperationId")
                        .IsUnique()
                        .HasFilter("[OperationId] IS NOT NULL");

                    b.HasIndex("SaleId");

                    b.ToTable("SalePayments", "dbo");
                });

            modelBuilder.Entity("StorePos.Domain.Aggregates.User.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", "dbo");
                });

            modelBuilder.Entity("StorePos.Domain.Aggregates.Product.Product", b =>
                {
                    b.HasOne("StorePos.Domain.Aggregates.MeasurementUnit.MeasurementUnit", null)
                        .WithMany()
                        .HasForeignKey("MeasurementUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("StorePos.Domain.Aggregates.Sale.Sale", b =>
                {
                    b.HasOne("StorePos.Domain.Aggregates.User.User", null)
                        .WithMany()
                        .HasForeignKey("CashierId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("StorePos.Domain.Aggregates.Customer.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("StorePos.Domain.Aggregates.Sale.SaleItem", b =>
                {
                    b.HasOne("StorePos.Domain.Aggregates.MeasurementUnit.MeasurementUnit", null)
                        .WithMany()
                        .HasForeignKey("MeasurementUnitId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("StorePos.Domain.Aggregates.Product.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("StorePos.Domain.Aggregates.Sale.Sale", null)
                        .WithMany("Items")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StorePos.Domain.Aggregates.Sale.SalePayment", b =>
                {
                    b.HasOne("StorePos.Domain.Aggregates.Sale.Sale", null)
                        .WithMany("Payments")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StorePos.Domain.Aggregates.Sale.Sale", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
